spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: app1
          uri: http://dummyservice1
          predicates:
            - Path=/red
          filters:
            - StripPrefix=1

        - id: app2
          uri: http://dummyservice2
          predicates:
            - Path=/blue
          filters:
            - StripPrefix=1
